# AniData Lab : Rapport d'Audit Du Dataset

## Objectifs de cet audit

1. Explorer les 3 fichiers CSV sources (anime, ratings, synopsis)
2. Identifier les problèmes de qualité : valeurs manquantes, doublons, types incohérents, encodages
3. Produire des statistiques descriptives et un profiling automatisé
4. Documenter les anomalies et recommandations de nettoyage

# 1 Mise En Place et Chargement Des Données

In [23]:
import numpy as np
import pandas as pd

In [24]:
#Grand DF, pandas trinque beaucoup de colonnes
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [25]:
# Variablisation du repertoire source pour meilleur robustesse 
REP_SOURCE = "../data"

In [ ]:
animelist = pd.read_csv(f"{REP_SOURCE}/animelist.csv")
anime = pd.read_csv(f"{REP_SOURCE}/anime.csv", encoding='utf-8') #Verfication encodage des données
rating_complete = pd.read_csv(f"{REP_SOURCE}/rating_complete.csv")
anime_with_synopsis = pd.read_csv(f"{REP_SOURCE}/anime_with_synopsis.csv")

# 2 EDA, Nettoyage et Audit de animelist

In [27]:
animelist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109224747 entries, 0 to 109224746
Data columns (total 5 columns):
 #   Column            Dtype
---  ------            -----
 0   user_id           int64
 1   anime_id          int64
 2   rating            int64
 3   watching_status   int64
 4   watched_episodes  int64
dtypes: int64(5)
memory usage: 4.1 GB

In [28]:
animelist.isnull().sum()

user_id             0
anime_id            0
rating              0
watching_status     0
watched_episodes    0
dtype: int64

In [29]:
animelist.describe()

,user_id,anime_id,rating,watching_status,watched_episodes
count,1.092247e+08,1.092247e+08,1.092247e+08,1.092247e+08,1.092247e+08
mean,1.768098e+05,1.649590e+04,4.245717e+00,3.087289e+00,1.210818e+01
std,1.018487e+05,1.379737e+04,3.912888e+00,1.774407e+00,1.463155e+02
min,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.849100e+04,3.194000e+03,0.000000e+00,2.000000e+00,0.000000e+00
50%,1.771420e+05,1.244500e+04,5.000000e+00,2.000000e+00,3.000000e+00
75%,2.651870e+05,3.083100e+04,8.000000e+00,6.000000e+00,1.200000e+01
max,3.534040e+05,4.849200e+04,1.000000e+01,5.500000e+01,6.553500e+04

In [30]:
animelist.head()

   user_id  anime_id  rating  watching_status  watched_episodes
0        0        67       9                1                 1
1        0      6702       7                1                 4
2        0       242      10                1                 4
3        0      4898       0                1                 1
4        0        21      10                1                 0

In [31]:
nb_null_animelist = animelist.duplicated().sum()
print(nb_null_animelist)

1

In [32]:
animelist = animelist.drop_duplicates()
nb_null_animelist = animelist.duplicated().sum()
print(nb_null_animelist)

0

In [33]:
animelist[["user_id", "anime_id"]].duplicated().sum()

np.int64(0)

In [34]:
animelist["rating"].value_counts()

rating
0     46827034
8     15422150
7     14244633
9     10235934
6      7543377
10     7144392
5      4029645
4      1845854
3       905700
2       545339
1       480688
Name: count, dtype: int64

In [35]:
animelist["watching_status"].unique()

array([ 1,  2,  3,  4,  6,  0,  5, 33, 55])

In [36]:
animelist["watching_status"].value_counts()

watching_status
2     68089751
6     27938692
1      5228658
4      4266591
3      3700514
0          531
5            6
33           2
55           1
Name: count, dtype: int64

In [37]:
animelist["watching_status"] = animelist["watching_status"].replace({33: 3, 55: 5})

In [38]:
animelist["watching_status"].value_counts()

watching_status
2    68089751
6    27938692
1     5228658
4     4266591
3     3700516
0         531
5           7
Name: count, dtype: int64

In [39]:
animelist["watched_episodes"].value_counts()

watched_episodes
0        31436236
1        18649591
12       18012508
13        8150010
24        4145984
2         3565169
25        3455815
26        3322520
3         2103188
4         1842437
10        1619294
6         1521060
11        1434279
5         1010156
22         744959
7          641069
8          634506
51         517208
9          461086
14         375801
23         367032
50         311896
52         256587
15         248753
64         246929
37         219826
20         217161
39         196258
27         158770
220        140591
16         134547
43         102728
21          97155
148         91914
291         80475
49          78221
38          77593
175         77334
153         75632
47          74997
18          73664
366         67835
276         64096
500         62615
17          62423
75          58070
54          53911
19          52005
48          51529
46          51063
102         51020
60          50683
167         47166
103         44895
120         44806
74          44725
70          44582
112         39035
201         38761
62          37486
224         35585
203         34826
30          34528
40          34466
97          31509
131         31488
78          27940
45          27518
73          25752
34          24827
94          24492
192         24087
35          24010
101         22986
36          22402
100         20434
180         20051
29          18833
76          18759
161         18695
42          18538
61          18236
77          17584
44          17283
114         17154
178         16865
95          16572
191         15825
145         14840
32          14591
33          14442
104         14108
110         13443
28          13357
127         13291
65          12584
150         12555
128         12279
69          12216
31          11915
93          11446
84          11322
56          10707
154         10525
99          10313
67           9271
109          8265
41           7848
63           7564
55           6811
58           6547
147          6387
96           5922
80           5855
296          5459
53           5318
59           4989
115          4801
79           4719
130          4633
90           4390
105          4363
200          4339
1787         4233
66           4181
72           4166
146          3837
68           3703
140          3527
155          3468
57           3099
91           3029
195          3005
92           3004
135          2859
358          2852
113          2738
142          2705
108          2594
300          2432
124          2424
172          2410
132          2391
86           2342
85           2341
71           2289
160          2253
125          2155
214          2092
165          2082
137          2056
83           2042
166          2034
136          2031
81           2018
82           2017
170          1996
88           1977
89           1973
87           1867
98           1629
156          1606
122          1567
965          1542
123          1525
126          1515
243          1510
111          1495
121          1472
117          1471
9001         1467
134          1467
164          1465
143          1457
310          1447
106          1437
151          1425
250          1406
133          1378
138          1365
193          1344
107          1334
144          1333
168          1303
141          1295
400          1291
118          1264
119          1250
694          1225
129          1224
116          1224
157          1216
158          1204
163          1163
190          1104
139          1103
964          1102
162          1098
152          1062
159          1042
189           985
373           952
700           949
600           931
188           896
350           838
331           836
330           827
963           775
169           767
900           762
800           741
149           735
210           714
187           694
929           660
320           646
230           642
182           612
174           597
270           595
176           574
173           574
240           567
185           566
171           561
184           547
260           539
960           536
181           529
186           522
280           519
183           514
526           509
205           509
956           508
962           502
256           488
179           485
746           485
343           482
750           478
312           476
450           474
272           473
222           465
311           464
177           463
255           458
215           455
290           454
302           449
65535         448
340           448
325           445
309           437
365           433
225           433
206           425
212           422
958           417
961           417
202           413
957           413
305           403
345           400
198           393
950           393
258           393
265           391
219           388
226           386
207           382
426           381
223           380
367           380
420           379
393           378
275           375
650           372
333           368
380           368
479           367
360           364
196           364
342           362
211           359
266           358
194           357
344           353
216           352
217           351
301           350
316           349
959           344
267           344
204           341
574           340
322           338
197           336
213           333
208           333
480           333
425           333
237           331
199           328
245           328
283           327
251           326
218           326
273           318
303           315
254           313
228           312
930           308
1000          307
229           307
221           304
263           303
308           303
317           302
268           302
357           297
269           296
271           295
390           293
315           292
285           290
278           290
321           288
347           287
334           286
209           285
375           283
274           283
430           282
253           279
324           277
227           273
346           272
550           270
348           270
381           269
284           269
306           268
920           268
234           265
928           264
630           264
289           264
257           263
335           263
304           262
295           262
244           261
252           261
235           261
242           260
385           259
246           257
915           256
231           253
680           253
580           251
277           250
336           248
516           248
341           248
279           245
940           245
475           245
249           245
955           243
850           240
625           240
314           240
421           240
337           240
313           240
323           237
307           237
370           236
236           236
326           235
470           235
384           235
286           235
232           234
261           233
740           233
745           232
247           232
262           231
264           231
726           230
415           230
490           229
281           229
378           229
891           229
352           228
356           227
288           227
880           224
530           224
297           224
233           223
890           222
902           219
351           219
298           219
578           217
999           217
756           216
830           215
299           214
319           214
945           214
318           214
349           214
910           214
329           214
248           214
362           213
747           213
752           213
363           212
954           212
282           212
432           211
628           210
751           210
520           210
460           208
926           208
238           207
364           207
383           207
332           207
770           207
241           207
720           205
394           204
387           203
339           202
540           200
414           199
892           199
328           198
424           197
570           197
837           196
294           195
388           195
431           194
382           193
893           193
710           193
483           193
355           191
923           191
459           191
354           191
780           190
889           190
489           190
942           190
690           189
287           189
820           188
338           188
925           188
416           188
944           187
361           187
259           187
916           185
735           185
783           184
368           183
392           183
405           182
440           182
810           181
670           181
372           181
782           181
293           181
730           180
901           180
734           180
903           180
620           179
374           179
877           179
790           178
418           178
943           177
905           176
629           176
760           176
478           176
410           175
974           174
435           174
391           174
386           174
327           173
779           172
353           172
458           171
927           169
402           167
935           167
808           167
560           166
654           166
878           166
724           166
894           165
433           165
428           164
465           164
947           164
666           164
917           164
879           164
239           164
488           163
951           163
401           163
835           162
590           162
456           161
522           161
427           161
379           161
948           160
477           160
417           159
938           159
932           159
870           158
640           158
931           157
936           157
463           157
953           156
610           155
579           153
904           153
685           153
485           153
292           152
934           152
481           151
451           151
434           151
585           150
946           149
575           149
736           149
753           149
908           149
525           148
826           148
860           147
601           147
706           147
906           146
491           146
423           146
895           146
785           146
898           146
457           145
744           145
755           145
443           144
419           144
484           144
748           143
395           143
581           143
952           143
949           143
711           143
529           142
682           142
937           142
897           141
840           141
452           140
412           140
626           140
527           140
733           139
699           139
728           139
413           139
660           139
359           139
812           138
605           137
773           137
429           137
732           137
523           136
701           136
651           136
941           135
919           135
899           134
924           134
517           134
702           134
801           134
825           133
445           133
704           133
589           133
739           132
602           132
691           132
635           132
404           132
567           131
377           131
762           131
482           131
455           130
939           130
757           130
836           129
793           129
921           129
819           129
789           129
914           128
453           128
582           128
758           127
834           127
844           127
799           127
467           126
827           126
725           126
422           125
510           125
528           125
737           124
723           124
705           124
777           123
573           123
603           123
437           122
794           122
403           122
875           122
786           122
741           122
683           122
631           122
765           121
909           121
688           121
555           120
464           120
692           120
911           120
655           120
907           120
369           120
727           119
667           118
474           118
788           118
852           118
881           117
709           117
442           117
738           116
913           116
681           116
715           116
371           115
771           115
729           115
623           115
791           115
486           115
472           114
541           114
912           114
772           114
742           114
743           114
918           114
792           114
524           113
787           113
411           113
888           113
803           113
845           112
675           112
687           112
587           112
436           112
933           111
583           111
468           111
1471          111
712           111
396           111
698           111
686           110
663           110
754           109
444           109
774           109
896           109
689           109
407           109
493           108
811           108
591           108
802           108
461           108
487           107
656           107
652           107
874           107
707           107
658           107
399           106
795           106
606           106
653           106
565           106
678           106
471           105
521           105
476           105
759           105
647           105
454           105
448           105
866           105
408           104
769           104
586           104
821           104
703           103
885           103
778           103
1818          103
882           103
842           103
588           103
815           103
469           102
558           102
813           102
684           102
645           102
784           102
856           102
537           102
708           102
512           101
1001          101
763           101
622           101
577           101
538           101
697           101
676           101
473           101
532           101
832           100
823           100
584           100
627           100
693           100
495            99
571            99
621            99
804            99
632            99
922            99
376            99
615            99
441            98
764            98
809            98
695            98
858            98
854            98
556            98
609            98
797            98
781            97
531            97
828            97
462            97
855            97
563            97
566            97
805            96
776            96
833            96
624            96
572            96
438            95
613            95
816            95
398            95
466            95
665            95
775            95
554            94
679            94
659            94
409            94
569            94
633            94
592            94
389            94
841            94
607            93
612            93
611            93
439            93
535            93
846            93
614            92
664            92
406            92
847            92
814            92
829            92
642            92
873            92
995            91
639            91
504            91
643            91
867            91
713            90
851            90
824            90
768            90
716            90
717            90
638            90
595            90
749            90
608            90
646            89
876            89
766            89
806            89
767            89
796            89
568            89
672            88
722            88
657            88
838            88
843            87
848            87
662            87
721            87
397            87
593            87
518            87
822            87
871            86
576            86
817            86
446            85
853            85
533            85
884            85
674            85
596            85
539            85
761            84
714            84
501            83
661            83
1337           83
673            83
641            83
494            82
872            82
818            82
594            82
637            82
1428           82
534            82
984            82
636            82
649            81
831            81
559            81
604            80
719            80
669            80
857            80
677            80
543            80
515            80
507            80
597            79
617            79
544            79
839            79
863            79
731            78
536            78
492            78
619            78
887            78
618            78
886            78
598            78
668            78
862            77
557            77
644            76
883            76
447            75
859            75
616            75
561            75
696            74
634            73
718            73
449            73
545            73
671            73
798            73
496            72
861            72
552            72
547            71
564            70
514            69
1006           69
519            67
499            67
648            67
513            67
562            67
865            66
549            66
553            66
599            66
869            66
546            65
864            64
849            62
503            62
548            62
502            61
506            60
542            60
1565           60
868            58
998            58
505            58
509            58
511            58
966            56
508            55
497            55
980            55
498            55
807            53
992            53
975            52
997            52
551            52
996            51
1274           50
1306           41
988            40
970            39
968            36
2000           34
9999           33
990            31
982            28
994            28
983            28
985            25
3057           25
967            23
989            23
986            23
973            23
993            22
978            22
991            22
64455          22
1500           20
977            20
976            20
987            19
9000           19
969            18
971            17
979            17
981            15
1234           15
10000          14
1200           14
1007           13
1035           11
972            11
1300           11
7000           11
7466            9
1450            9
1100            8
3000            7
1052            7
20000           7
7071            7
2222            7
7542            6
1019            6
1111            6
1010            6
1600            5
1002            5
8000            5
5000            5
6000            5
2011            4
1599            4
2444            4
1036            4
1087            4
1551            4
1064            4
1324            4
7600            3
1031            3
1069            3
7500            3
2061            3
1075            3
1488            3
1025            3
1038            3
1357            3
1250            3
8956            3
6500            3
1050            3
7701            3
1034            3
1005            3
1020            3
1767            3
1288            3
1587            3
1808            3
1400            3
1245            3
1003            3
1888            3
1041            3
1700            3
12799           3
1126            3
1310            3
2169            3
1086            3
1800            3
4444            2
1761            2
1040            2
1243            2
1786            2
2555            2
7700            2
1021            2
2626            2
19999           2
1028            2
1463            2
1078            2
1878            2
1023            2
1014            2
2500            2
1032            2
2583            2
4000            2
1029            2
1015            2
1043            2
1210            2
1046            2

In [40]:
animelist[animelist["watched_episodes"] > 500].value_counts()

user_id  anime_id  rating  watching_status  watched_episodes
1        21        9       1                958                 1
11       21        10      1                756                 1
14       21        8       4                689                 1
15       21        0       1                965                 1
30       21        8       3                705                 1
40       21        10      1                803                 1
43       21        9       1                692                 1
48       21        10      1                788                 1
50       21        10      1                825                 1
51       21        9       1                756                 1
55       21        10      1                580                 1
60       21        0       1                697                 1
66       2471      0       2                1787                1
71       21        0       1                697                 1
80       21        8       1                579                 1
81       21        10      1                877                 1
83       21        9       1                956                 1
84       21        0       1                614                 1
101      21        10      1                776                 1
108      21        9       3                743                 1
110      21        10      1                948                 1
111      21        0       1                956                 1
112      21        7       1                798                 1
117      21        8       1                947                 1
127      21        9       3                579                 1
128      21        10      1                655                 1
131      21        9       1                705                 1
145      21        8       3                602                 1
147      235       10      1                975                 1
169      21        9       3                640                 1
172      21        10      1                807                 1
181      21        0       1                900                 1
190      21        0       1                843                 1
198      235       0       1                915                 1
201      21        10      1                680                 1
204      21        4       4                670                 1
205      21        10      1                911                 1
209      21        7       1                715                 1
217      21        8       3                700                 1
219      21        10      1                530                 1
224      21        10      1                663                 1
226      21        10      1                684                 1
231      21        9       1                908                 1
237      4936      0       2                694                 1
240      21        0       3                834                 1
247      21        9       1                520                 1
248      21        9       1                891                 1
251      21        8       1                700                 1
252      21        0       1                782                 1
258      21        10      1                965                 1
268      235       10      1                813                 1
272      21        7       3                913                 1
         235       7       3                815                 1
274      21        0       1                695                 1
         235       0       1                848                 1
284      21        10      1                897                 1
285      21        10      1                959                 1
287      21        10      1                946                 1
         2471      10      2                1787                1
289      21        9       1                597                 1
         235       10      1                650                 1
294      21        0       1                960                 1
301      21        0       3                929                 1
308      21        0       1                703                 1
310      21        10      1                958                 1
314      21        9       1                894                 1
321      21        9       1                733                 1
326      21        8       3                541                 1
327      21        0       1                832                 1
336      21        7       1                965                 1
339      21        9       1                798                 1
345      21        10      1                726                 1
346      21        0       1                964                 1
347      21        8       3                578                 1
350      21        10      1                928                 1
351      21        10      1                835                 1
358      2471      0       2                1787                1
         4936      0       2                694                 1
367      235       0       1                874                 1
371      21        6       4                600                 1
375      21        0       1                879                 1
377      21        9       1                527                 1
381      21        8       1                580                 1
402      21        0       3                915                 1
404      21        0       1                523                 1
406      21        10      3                673                 1
413      21        9       3                692                 1
414      21        9       1                747                 1
         235       8       1                600                 1
         2471      9       2                1787                1
418      966       8       3                761                 1
         2471      7       2                1787                1
423      21        9       1                600                 1
430      21        10      1                929                 1
431      21        8       1                842                 1
433      21        7       1                870                 1
440      21        9       1                546                 1
442      21        10      1                735                 1
445      2471      7       2                1787                1
         4936      7       2                694                 1
446      21        8       1                880                 1
454      21        10      1                897                 1
459      21        0       3                577                 1
460      21        10      1                909                 1
463      21        10      1                800                 1
480      21        7       3                739                 1
500      21        10      3                758                 1
504      21        8       1                875                 1
509      21        6       4                630                 1
511      21        10      1                743                 1
516      21        0       1                800                 1
         235       10      1                1500                1
532      21        8       1                955                 1
541      21        10      1                963                 1
549      21        0       1                901                 1
554      21        8       1                903                 1
564      21        10      3                808                 1
566      21        10      1                800                 1
         235       8       1                600                 1
         2471      8       1                1000                1
573      21        10      1                544                 1
576      21        10      1                873                 1
581      21        0       3                808                 1
585      21        10      3                607                 1
595      21        10      1                704                 1
599      21        10      1                730                 1
601      21        9       3                684                 1
607      21        10      3                899                 1
610      21        10      1                904                 1
612      235       0       1                587                 1
         1199      0       1                1400                1
629      21        8       1                880                 1
631      3221      6       2                9001                1
634      21        0       1                629                 1
639      21        8       1                955                 1
         235       10      1                991                 1
642      21        10      1                965                 1
644      21        0       4                566                 1
645      21        0       1                705                 1
649      21        0       4                666                 1
650      21        3       4                625                 1
651      21        10      1                965                 1
653      21        10      3                750                 1
656      21        7       1                36600               1
657      21        8       3                638                 1
662      21        10      1                929                 1
         235       10      1                974                 1
664      21        10      4                566                 1
668      21        10      1                655                 1
         235       10      1                677                 1
671      21        0       1                507                 1
673      21        8       1                899                 1
675      21        7       4                665                 1
676      21        10      3                924                 1
688      21        10      1                710                 1
691      21        8       1                676                 1
694      21        10      1                838                 1
         235       10      3                587                 1
696      21        8       1                508                 1
702      21        10      1                959                 1
711      21        0       3                848                 1
719      21        10      1                530                 1
720      21        0       1                956                 1
721      21        10      1                728                 1
722      3342      6       2                9001                1
725      21        0       1                963                 1
746      21        7       3                791                 1
753      21        9       1                964                 1
754      2406      0       1                992                 1
755      21        10      1                587                 1
759      21        8       1                623                 1
763      21        10      1                598                 1
765      21        0       1                924                 1
770      21        9       1                924                 1
773      21        10      1                959                 1
776      21        10      1                729                 1
779      21        9       1                800                 1
781      21        7       1                965                 1
783      21        0       1                964                 1
784      21        9       3                693                 1
786      21        8       1                515                 1
792      966       0       4                902                 1
         2471      6       2                1787                1
         4936      5       2                694                 1
         11595     4       2                526                 1
801      235       8       1                751                 1
809      21        10      1                916                 1
811      21        10      1                910                 1
814      21        9       1                761                 1
818      21        8       3                746                 1
826      21        9       3                526                 1
830      21        0       1                807                 1
843      21        0       3                550                 1
848      21        0       1                756                 1
849      21        10      1                963                 1
851      21        6       1                901                 1
852      21        0       1                885                 1
853      235       7       1                974                 1
858      21        10      1                599                 1
861      21        10      1                600                 1
         235       10      1                550                 1
864      21        0       3                575                 1
870      21        0       1                772                 1
876      21        6       3                748                 1
877      21        9       1                704                 1
878      21        9       1                837                 1
879      21        10      1                857                 1
886      21        10      1                700                 1
887      21        8       1                506                 1
888      21        8       3                834                 1
894      21        10      1                779                 1
895      21        10      1                944                 1
908      2471      9       2                1787                1
912      21        8       3                866                 1
915      21        0       4                530                 1
916      21        0       3                915                 1
918      21        10      1                746                 1
923      21        7       1                748                 1
925      21        0       1                959                 1
         235       0       1                783                 1
928      21        10      1                659                 1
932      21        9       1                920                 1
936      21        10      1                956                 1
         235       8       1                644                 1
938      21        0       3                790                 1
939      21        10      1                963                 1
943      21        0       1                963                 1
         2471      8       2                1787                1
         4936      7       2                694                 1
944      21        0       3                656                 1
945      21        0       1                960                 1
969      21        9       1                965                 1
         966       8       4                700                 1
971      21        10      1                695                 1
976      21        9       1                949                 1
984      21        10      1                938                 1
992      21        10      1                912                 1
995      21        8       3                798                 1
         2471      8       2                1787                1
         4936      8       2                694                 1
         8687      8       3                581                 1
         11595     9       2                526                 1
998      235       9       3                567                 1
1004     21        9       1                806                 1
1008     21        8       3                649                 1
1010     21        7       1                727                 1
1023     21        9       1                800                 1
1038     21        0       3                757                 1
1043     21        10      1                657                 1
1054     21        10      1                952                 1
1060     21        10      1                582                 1
1065     21        10      1                747                 1
1066     21        10      1                940                 1
1069     21        10      1                916                 1
1075     21        0       1                727                 1
1081     21        10      1                764                 1
1087     21        10      1                934                 1
1088     21        10      1                965                 1
1092     21        10      1                963                 1
1099     21        10      1                540                 1
1101     21        8       1                651                 1
1111     21        10      1                650                 1
1112     21        10      1                858                 1
1113     21        5       4                587                 1
1115     21        10      1                588                 1
1119     21        7       1                783                 1
1125     355       5       2                9001                1
1127     21        10      1                929                 1
1135     21        10      1                910                 1
1139     21        0       4                586                 1
1149     21        10      1                715                 1
1150     21        7       3                585                 1
1151     21        10      1                525                 1
1160     21        0       1                710                 1
1177     2471      7       2                1787                1
         4936      6       2                694                 1
         6277      7       2                1471                1
1184     21        10      1                939                 1
1187     21        0       1                891                 1
1192     235       0       1                581                 1
1201     21        0       1                741                 1
1205     21        9       1                620                 1
         235       9       1                836                 1
1209     21        0       1                778                 1
1210     21        10      3                575                 1
1212     21        10      1                921                 1
1219     21        0       1                936                 1
1220     21        0       3                521                 1
1221     21        6       1                722                 1
1227     21        0       4                710                 1
1229     21        10      1                588                 1
1234     21        10      1                529                 1
         235       10      3                648                 1
1240     21        8       1                706                 1
1242     21        0       1                752                 1
         235       0       1                816                 1
1246     21        9       3                746                 1
1249     21        8       1                802                 1
1272     21        10      1                793                 1
1277     21        0       4                775                 1
1285     21        9       1                738                 1
1286     21        9       1                622                 1

In [41]:
animelist["watched_episodes"].unique()

array([   1,    4,    0, ..., 1266, 1039, 6688], shape=(1464,))

In [42]:
animelist["watched_episodes"].unique().max()

np.int64(65535)

In [43]:
animelist[animelist["watched_episodes"] == 65535]

           user_id  anime_id  rating  watching_status  watched_episodes
1040262       3546      1636      10                1             65535
1040263       3546      1896       0                1             65535
1572985       5411     34572      10                1             65535
1966788       6695     32977       6                1             65535
1966789       6695     34566       7                1             65535
1966791       6695      6149       8                1             65535
1966792       6695       966       7                1             65535
1966793       6695       235       6                1             65535
1966794       6695      8687       7                1             65535
1966796       6695     36838       6                1             65535
1966798       6695     30151       8                1             65535
1966800       6695      1199       6                1             65535
1966801       6695        21       8                1             65535
1966803       6695      2406       7                1             65535
1966804       6695     34866       7                1             65535
1967047       6695     35510       7                6             65535
4086365      13452       235       0                1             65535
4086366      13452        21       0                1             65535
4095263      13478      1576       0                2             65535
4095264      13478      1682       0                2             65535
4095268      13478      1686       0                2             65535
4095278      13478      1575       1                2             65535
4095282      13478      1683       0                2             65535
4095283      13478      1684       0                2             65535
4095284      13478      1685       0                2             65535
4095309      13478        33      10                2             65535
4095311      13478      1579       0                2             65535
4095312      13478      1578       0                2             65535
4095313      13478        43       0                2             65535
4095320      13478      1580       0                2             65535
4095323      13478        30       1                2             65535
4095324      13478        31       1                2             65535
4095325      13478        32       0                2             65535
4095348      13478      1577       0                2             65535
4160086      13717      4866      10                2             65535
4160087      13717      6546      10                2             65535
4752669      15686       966      10                1             65535
4911605      16212        21       1                4             65535
7136369      23409     32483       1                1             65535
7136397      23409     31845      10                1             65535
7136406      23409     31229       1                1             65535
7455683      24447     34566      10                1             65535
7455833      24447        21       7                3             65535
8212573      26789       235       0                6             65535
8564051      27960        21       6                3             65535
8667498      28301     35639       0                1             65535
8668046      28301     37869       0                6             65535
8668055      28301     35712       0                6             65535
8668063      28301     31456       0                6             65535
8668105      28301     35557       0                6             65535
8668111      28301     35076       0                6             65535
8668156      28301     36198       0                6             65535
8668163      28301     36632       0                6             65535
8668200      28301     35838       0                6             65535
9647188      31466       269       0                1             65535
10334470     33662       966       0                3             65535
11932235     38798      8687       8                3             65535
11950565     38864     34566       1                1             65535
15242344     49487     18893       0                6             65535
15242345     49487       889       0                6             65535
15242379     49487     16353       0                6             65535
15242383     49487     25517       0                6             65535
15242402     49487       529       0                6             65535
15449035     50158       235       7                4             65535
17067076     55312        21       9                1             65535
19743427     63795      2406       5                6             65535
19743431     63795     39551       0                6             65535
20470269     66203        21       0                4             65535
21677019     70149     34572       7                1             65535
22755595     73642        21       8                3             65535
22755620     73642      2406       0                4             65535
23464598     75990        21       0                1             65535
24158795     78359     34572      10                3             65535
24158869     78359     38814       5                4             65535
25944658     84148        21       8                1             65535
26144738     84812        21       0                4             65535
26635079     86303        21      10                1             65535
26813156     86893        21      10                1             65535
27163207     88012      9947       5                1             65535
29349333     95140       355       8                2             65535
29349349     95140      1735       3                3             65535
29349350     95140       269       2                4             65535
29608032     95947      5042       8                1             65535
31047874    100624     42498       8                1             65535
31047889    100624     39551       8                1             65535
31047977    100624     28755       6                2             65535
31047980    100624      6772       7                2             65535
31047981    100624      8514       7                2             65535
31047982    100624      9252       7                2             65535
31047983    100624      9465       7                2             65535
31047984    100624      9724       7                2             65535
31047985    100624     10092       6                2             65535
31047999    100624       371       6                2             65535
31048000    100624       372       8                2             65535
31048037    100624     10029       6                2             65535
31048058    100624     24655       5                2             65535
31048063    100624     10638       5                2             65535
31048152    100624       820      10                2             65535
31048181    100624     16528       7                2             65535
31048186    100624     14175       7                2             65535
31048208    100624     10765       6                2             65535
31048214    100624       578       7                2             65535
31048215    100624     10408       7                2             65535
31048219    100624     13271       5                2             65535
31048220    100624     19951       4                2             65535
31048266    100624      9617       7                2             65535
31048295    100624      7711       6                2             65535
31048299    100624     16662       7                2             65535
31048311    100624      2454       7                2             65535
31048346    100624     16782       7                2             65535
31048383    100624      5310       7                2             65535
31048384    100624      7222       7                2             65535
31048397    100624      4985       7                2             65535
31048435    100624       593       7                2             65535
31048454    100624     13667       6                2             65535
31048491    100624      1029       8                2             65535
31048538    100624       758       7                2             65535
31048566    100624     10334       5                2             65535
31048609    100624       199       6                2             65535
31048611    100624      9793       4                2             65535
31048625    100624      2098       6                2             65535
31048651    100624      8407       6                2             65535
31048653    100624      9790       4                2             65535
31048659    100624     21469       7                2             65535
31048661    100624     11577       7                2             65535
31048663    100624      2418       6                2             65535
31048670    100624      7311       7                2             65535
31048701    100624      9000       7                2             65535
31048711    100624     11743       6                2             65535
31048724    100624      1539       4                2             65535
31048765    100624     10532       6                2             65535
31048773    100624     18753       6                2             65535
31048921    100624      1735       0                4             65535
31626295    102570     34572       0                4             65535
32141998    104268        21       0                1             65535
32355403    104989        21       6                4             65535
34101260    110606      2406       0                4             65535
35641643    115661     35849       0                1             65535
35641644    115661     34497       0                1             65535
35641646    115661     34279       1                1             65535
35641650    115661     34577       0                1             65535
35641653    115661     33352       1                1             65535
35642465    115661     34566       1                3             65535
35642502    115661     32977       1                4             65535
35642503    115661     32717       1                4             65535
35642505    115661     35226       2                4             65535
35642512    115661     33044       1                4             65535
35642514    115661     36516       1                4             65535
35642516    115661     34901       2                4             65535
35642523    115661     32353       2                4             65535
35642528    115661     36022       2                4             65535
35642529    115661     35517       2                4             65535
35642547    115661     34905       1                4             65535
35642553    115661     33047       1                4             65535
35642554    115661     35319       1                4             65535
35642556    115661     34836       1                4             65535
35642561    115661     36797       1                4             65535
35642572    115661     35889       1                4             65535
35642576    115661     36784       1                4             65535
35642581    115661     36593       1                4             65535
35642583    115661     36894       0                4             65535
35642586    115661     30151       2                4             65535
35642589    115661     34964       1                4             65535
35642590    115661     36548       1                4             65535
35642595    115661      9947       1                4             65535
35642596    115661     33782       1                4             65535
35642601    115661     36728       1                4             65535
35642609    115661     33946       2                4             65535
35642611    115661     31631       1                4             65535
35642615    115661     36847       1                4             65535
35642617    115661     33398       1                4             65535
35642618    115661     35478       1                4             65535
35642619    115661     35444       1                4             65535
35642620    115661     36907       1                4             65535
35642622    115661     24845       1                4             65535
35642623    115661     24403       2                4             65535
35642627    115661     36135       1                4             65535
35642641    115661     34927       1                4             65535
35642644    115661     35905       0                4             65535
35642645    115661     36815       1                4             65535
35642648    115661     10506       1                4             65535
35642650    115661     33540       1                4             65535
35642653    115661     34979       1                4             65535
35642660    115661     32585       1                4             65535
35642663    115661     35254       1                4             65535
35642673    115661     36409       1                4             65535
35642675    115661     34866       1                4             65535
35642676    115661     35957       1                4             65535
35642678    115661     34944       0                6             65535
35642679    115661     37338       0                6             65535
35642680    115661     27783       0                6             65535
37091243    120490       966       7                1             65535
37311401    121241     37991       0                6             65535
37876549    122976     34572       0                1             65535
37943794    123184       223       0                2             65535
38066083    123586     41623       0                6             65535
38138978    123846        21       0                1             65535
39078572    126903     38408       0                6             65535
39529139    128411     34566       0                1             65535
42802318    138792     34572      10                1             65535
42802321    138792        21       1                1             65535
42802358    138792     34566      10                3             65535
43163457    139996       966       4                1             65535
43787701    142040       235       7                1             65535
45730246    148295      1966       1                2             65535
45730256    148295      3874       1                2             65535
45730257    148295      2921       1                2             65535
45730265    148295      3232       1                2             65535
45730267    148295     10553       1                2             65535
45730269    148295      1269       1                2             65535
45730276    148295     18191       1                2             65535
45730285    148295      1672       1                2             65535
45730295    148295     10799       1                2             65535
45730309    148295     10967       1                2             65535
45730320    148295     13501       1                2             65535
45730334    148295       974       1                2             65535
45730344    148295      2661       1                2             65535
45730345    148295      8478       1                2             65535
45730370    148295      6062       1                2             65535
45730382    148295      6152       1                2             65535
45730386    148295      5684       1                2             65535
45730387    148295        73       1                2             65535
45730393    148295      8293       1                2             65535
45730396    148295      5688       1                2             65535
45730399    148295      9969       1                2             65535
45730411    148295     19751       1                2             65535
45730414    148295       650       1                2             65535
45730417    148295      8764       1                2             65535
45730418    148295     10906       1                2             65535
45730424    148295      1848       1                2             65535
45730425    148295      1902       1                2             65535
45730432    148295      9563       1                2             65535
45730443    148295      2958       1                2             65535
45730444    148295     16828       1                2             65535
45730447    148295      6463       1                2             65535
45730470    148295      8290       1                2             65535
45730483    148295     12579       1                2             65535
45730485    148295     11857       1                2             65535
45730487    148295      6375       1                2             65535
45730503    148295       144       1                2             65535
45730506    148295      1691       1                2             65535
45730516    148295      2927       1                2             65535
45730523    148295       250       1                2             65535
45730529    148295      5557       1                2             65535
45730535    148295      7294       1                2             65535
45730555    148295     11829       1                2             65535
45730559    148295      1806       1                2             65535
45730562    148295      1155       1                2             65535
45730572    148295      1091       1                2             65535
45730573    148295      1215       1                2             65535
45730585    148295     14657       1                2             65535
45730591    148295      8038       1                2             65535
45730598    148295      2233       1                2             65535
45730606    148295      2141       1                2             65535
45730613    148295      3895       1                2             65535
45730614    148295      5492       1                2             65535
45730615    148295      6275       1                2             65535
45730646    148295      1008       1                2             65535
45730648    148295     14249       1                2             65535
45730651    148295      9385       1                2             65535
45730672    148295      8677       1                2             65535
45730683    148295     15793       1                2             65535
45730689    148295      2276       1                2             65535
45730695    148295      2348       1                2             65535
45730710    148295     17821       1                2             65535
45730726    148295     12015       1                2             65535
45730737    148295       415       1                2             65535
45730746    148295      1920       1                2             65535
45730753    148295      4700       1                2             65535
45730762    148295      4660       1                2             65535
47341069    153652       235       0                1             65535
47341116    153652      2406       0                1             65535
47846673    155354      2406       0                1             65535
48027491    155955        21      10                1             65535
48304050    156756       966      10                1             65535
49449883    160348        21      10                1             65535

Données potentiellement abérentes. différents animes ont l'air  d'avoir le même nombre d'episodes mais certaines lignes sont marqué finis et d'autres encours avec le même nombre d'épisode vu? Un autre dataset sera necessaire pour corriger ce point de données et d'autres potentiel données abérentes.

In [44]:
animelist["watched_episodes"].unique().min()

np.int64(0)

In [45]:
animelist["watched_episodes"].describe()

count    1.092247e+08
mean     1.210818e+01
std      1.463155e+02
min      0.000000e+00
25%      0.000000e+00
50%      3.000000e+00
75%      1.200000e+01
max      6.553500e+04
Name: watched_episodes, dtype: float64

## Synthèse animelist

| Anomalie | Détail | Action |
|----------|--------|--------|
| 1 doublon exact | Ligne identique sur toutes les colonnes | Supprimé via `drop_duplicates()` |
| rating = 0 | 46.8M lignes (43% du dataset) | Valeur sentinelle = "pas encore noté", à distinguer des vraies notes |
| watching_status aberrants | 33 (2 lignes), 55 (1 ligne), 0 (531 lignes) | 33→3 et 55→5 corrigés. Status 0 = non documenté, à investiguer |
| watched_episodes = 65535 | 448 lignes, valeur = 2^16 - 1 | Overflow ou sentinelle, données aberrantes. Nécessite croisement avec anime.csv pour correction |

**Note :** Ce fichier fait 109M lignes (4.1 Go en mémoire). Il est mentionné comme optionnel dans le projet (challenge avancé). Le fichier principal pour les ratings est `rating_complete.csv`.

# 3 EDA, Nettoyage et Audit de anime

In [46]:
anime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17562 entries, 0 to 17561
Data columns (total 35 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MAL_ID         17562 non-null  int64
 1   Name           17562 non-null  object
 2   Score          17562 non-null  object
 3   Genres         17562 non-null  object
 4   English name   17562 non-null  object
 5   Japanese name  17562 non-null  object
 6   Type           17562 non-null  object
 7   Episodes       17562 non-null  object
 8   Aired          17562 non-null  object
 9   Premiered      17562 non-null  object
 10  Producers      17562 non-null  object
 11  Licensors      17562 non-null  object
 12  Studios        17562 non-null  object
 13  Source         17562 non-null  object
 14  Duration       17562 non-null  object
 15  Rating         17562 non-null  object
 16  Ranked         17562 non-null  object
 17  Popularity     17562 non-null  int64
 18  Members        17562 non-null  int64
 19  Favorites      17562 non-null  int64
 20  Watching       17562 non-null  int64
 21  Completed      17562 non-null  int64
 22  On-Hold        17562 non-null  int64
 23  Dropped        17562 non-null  int64
 24  Plan to Watch  17562 non-null  int64
 25  Score-10       17562 non-null  object
 26  Score-9        17562 non-null  object
 27  Score-8        17562 non-null  object
 28  Score-7        17562 non-null  object
 29  Score-6        17562 non-null  object
 30  Score-5        17562 non-null  object
 31  Score-4        17562 non-null  object
 32  Score-3        17562 non-null  object
 33  Score-2        17562 non-null  object
 34  Score-1        17562 non-null  object
dtypes: int64(9), object(26)
memory usage: 4.7+ MB

In [47]:
anime.isnull().sum()

MAL_ID           0
Name             0
Score            0
Genres           0
English name     0
Japanese name    0
Type             0
Episodes         0
Aired            0
Premiered        0
Producers        0
Licensors        0
Studios          0
Source           0
Duration         0
Rating           0
Ranked           0
Popularity       0
Members          0
Favorites        0
Watching         0
Completed        0
On-Hold          0
Dropped          0
Plan to Watch    0
Score-10         0
Score-9          0
Score-8          0
Score-7          0
Score-6          0
Score-5          0
Score-4          0
Score-3          0
Score-2          0
Score-1          0
dtype: int64

In [48]:
anime.head()

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,Producers,Licensors,Studios,Source,Duration,Rating,Ranked,Popularity,Members,Favorites,Watching,Completed,On-Hold,Dropped,Plan to Watch,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",Cowboy Bebop,カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,Bandai Visual,"Funimation, Bandai Entertainment",Sunrise,Original,24 min. per ep.,R - 17+ (violence & profanity),28.0,39,1251960,61971,105808,718161,71513,26678,329800,229170.0,182126.0,131625.0,62330.0,20688.0,8904.0,3184.0,1357.0,741.0,1580.0
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Cowboy Bebop:The Movie,カウボーイビバップ 天国の扉,Movie,1,"Sep 1, 2001",Unknown,"Sunrise, Bandai Visual",Sony Pictures Entertainment,Bones,Original,1 hr. 55 min.,R - 17+ (violence & profanity),159.0,518,273145,1174,4143,208333,1935,770,57964,30043.0,49201.0,49505.0,22632.0,5805.0,1877.0,577.0,221.0,109.0,379.0
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",Trigun,トライガン,TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,Victor Entertainment,"Funimation, Geneon Entertainment USA",Madhouse,Manga,24 min. per ep.,PG-13 - Teens 13 or older,266.0,201,558913,12944,29113,343492,25465,13925,146918,50229.0,75651.0,86142.0,49432.0,15376.0,5838.0,1965.0,664.0,316.0,533.0
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),TV,26,"Jul 2, 2002 to Dec 24, 2002",Summer 2002,"TV Tokyo, Bandai Visual, Dentsu, Victor Entert...","Funimation, Bandai Entertainment",Sunrise,Original,25 min. per ep.,PG-13 - Teens 13 or older,2481.0,1467,94683,587,4300,46165,5121,5378,33719,2182.0,4806.0,10128.0,11618.0,5709.0,2920.0,1083.0,353.0,164.0,131.0
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",Beet the Vandel Buster,冒険王ビィト,TV,52,"Sep 30, 2004 to Sep 29, 2005",Fall 2004,"TV Tokyo, Dentsu",Unknown,Toei Animation,Manga,23 min. per ep.,PG - Children,3710.0,4369,13224,18,642,7314,766,1108,3394,312.0,529.0,1242.0,1713.0,1068.0,634.0,265.0,83.0,50.0,27.0

In [49]:
anime = anime.replace('Unknown', np.nan)

In [50]:
anime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17562 entries, 0 to 17561
Data columns (total 35 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MAL_ID         17562 non-null  int64
 1   Name           17562 non-null  object
 2   Score          12421 non-null  object
 3   Genres         17499 non-null  object
 4   English name   6997 non-null   object
 5   Japanese name  17514 non-null  object
 6   Type           17525 non-null  object
 7   Episodes       17046 non-null  object
 8   Aired          17253 non-null  object
 9   Premiered      4745 non-null   object
 10  Producers      9768 non-null   object
 11  Licensors      3946 non-null   object
 12  Studios        10483 non-null  object
 13  Source         13995 non-null  object
 14  Duration       17007 non-null  object
 15  Rating         16874 non-null  object
 16  Ranked         15800 non-null  object
 17  Popularity     17562 non-null  int64
 18  Members        17562 non-null  int64
 19  Favorites      17562 non-null  int64
 20  Watching       17562 non-null  int64
 21  Completed      17562 non-null  int64
 22  On-Hold        17562 non-null  int64
 23  Dropped        17562 non-null  int64
 24  Plan to Watch  17562 non-null  int64
 25  Score-10       17125 non-null  object
 26  Score-9        14395 non-null  object
 27  Score-8        16191 non-null  object
 28  Score-7        17059 non-null  object
 29  Score-6        17051 non-null  object
 30  Score-5        16978 non-null  object
 31  Score-4        16585 non-null  object
 32  Score-3        16255 non-null  object
 33  Score-2        15965 non-null  object
 34  Score-1        17103 non-null  object
dtypes: int64(9), object(26)
memory usage: 4.7+ MB

In [51]:
anime.isnull().sum()

MAL_ID               0
Name                 0
Score             5141
Genres              63
English name     10565
Japanese name       48
Type                37
Episodes           516
Aired              309
Premiered        12817
Producers         7794
Licensors        13616
Studios           7079
Source            3567
Duration           555
Rating             688
Ranked            1762
Popularity           0
Members              0
Favorites            0
Watching             0
Completed            0
On-Hold              0
Dropped              0
Plan to Watch        0
Score-10           437
Score-9           3167
Score-8           1371
Score-7            503
Score-6            511
Score-5            584
Score-4            977
Score-3           1307
Score-2           1597
Score-1            459
dtype: int64

In [52]:
nb_null_anime = anime.duplicated().sum()
print(nb_null_anime)

0

In [53]:
anime["MAL_ID"].duplicated().sum()

np.int64(0)

In [54]:
anime["Name"].duplicated().sum()

np.int64(4)

In [55]:
anime[anime["Name"].duplicated(keep=False)]

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,Producers,Licensors,Studios,Source,Duration,Rating,Ranked,Popularity,Members,Favorites,Watching,Completed,On-Hold,Dropped,Plan to Watch,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
12826,35102,Hinamatsuri,6.79,"Historical, Kids",NaN,ひなまつり,OVA,1,NaN,NaN,NaN,NaN,NaN,Other,19 min.,G - All Ages,4486.0,10044,1201,2,52,399,17,92,641,22.0,18.0,38.0,58.0,21.0,12.0,6.0,4.0,1.0,5.0
12955,35279,Youkoso! Ecolo Shima,NaN,Kids,NaN,ようこそ！エコロ島,OVA,1,NaN,NaN,NaN,NaN,NaN,Original,17 min.,G - All Ages,13024.0,16791,100,0,7,21,2,35,35,4.0,NaN,NaN,4.0,2.0,2.0,NaN,NaN,NaN,4.0
13540,36296,Hinamatsuri,8.21,"Comedy, Sci-Fi, Seinen, Slice of Life, Superna...",Hinamatsuri,ヒナまつり,TV,12,"Apr 6, 2018 to Jun 22, 2018",Spring 2018,"Media Factory, Magic Capsule, Nippon Columbia,...",Funimation,feel.,Manga,23 min. per ep.,PG-13 - Teens 13 or older,298.0,391,347326,3265,27757,209253,9457,7827,93032,21484.0,49894.0,63480.0,29442.0,8408.0,2895.0,813.0,267.0,124.0,168.0
15379,39143,Youkoso! Ecolo Shima,NaN,Kids,NaN,ようこそ！ エコロ島,OVA,1,NaN,NaN,NaN,NaN,NaN,Original,17 min.,G - All Ages,13025.0,17368,54,0,1,9,2,21,21,2.0,NaN,NaN,1.0,2.0,NaN,1.0,NaN,NaN,2.0
16195,40496,Maou Gakuin no Futekigousha: Shijou Saikyou no...,7.34,"Action, Demons, Magic, Fantasy, School",The Misfit of Demon King Academy,魔王学院の不適合者 ～史上最強の魔王の始祖、転生して子孫たちの学校へ通う～,TV,13,"Jul 4, 2020 to Sep 26, 2020",Summer 2020,"Aniplex, Kadokawa",Aniplex of America,SILVER LINK.,Light novel,23 min. per ep.,R - 17+ (violence & profanity),2177.0,377,356060,3057,48873,236529,4880,9563,56215,18424.0,23990.0,50133.0,58622.0,27479.0,12119.0,5087.0,2364.0,1209.0,835.0
17543,48417,Maou Gakuin no Futekigousha: Shijou Saikyou no...,NaN,"Magic, Fantasy, School",NaN,魔王学院の不適合者 ～史上最強の魔王の始祖、転生して子孫たちの学校へ通う～,TV,NaN,NaN,NaN,Aniplex,NaN,SILVER LINK.,Light novel,NaN,R - 17+ (violence & profanity),NaN,2597,41425,281,7,5,11,1,41401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17544,48418,Maou Gakuin no Futekigousha: Shijou Saikyou no...,NaN,"Action, Demons, Magic, Fantasy, School",NaN,魔王学院の不適合者 ～史上最強の魔王の始祖、転生して子孫たちの学校へ通う～,TV,NaN,NaN,NaN,Aniplex,NaN,SILVER LINK.,Light novel,NaN,R - 17+ (violence & profanity),NaN,5731,7707,41,1,2,5,2,7697,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
anime['Score'] = pd.to_numeric(anime['Score'], errors='coerce')
anime['Episodes'] = pd.to_numeric(anime['Episodes'], errors='coerce')
anime['Ranked'] = pd.to_numeric(anime['Ranked'], errors='coerce')

In [57]:
score_cols = ['Score-1', 'Score-2', 'Score-3', 'Score-4', 'Score-5', 'Score-6', 'Score-7', 'Score-8', 'Score-9', 'Score-10']
anime[score_cols] = anime[score_cols].apply(pd.to_numeric, errors='coerce')

In [58]:
anime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17562 entries, 0 to 17561
Data columns (total 35 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MAL_ID         17562 non-null  int64
 1   Name           17562 non-null  object
 2   Score          12421 non-null  float64
 3   Genres         17499 non-null  object
 4   English name   6997 non-null   object
 5   Japanese name  17514 non-null  object
 6   Type           17525 non-null  object
 7   Episodes       17046 non-null  float64
 8   Aired          17253 non-null  object
 9   Premiered      4745 non-null   object
 10  Producers      9768 non-null   object
 11  Licensors      3946 non-null   object
 12  Studios        10483 non-null  object
 13  Source         13995 non-null  object
 14  Duration       17007 non-null  object
 15  Rating         16874 non-null  object
 16  Ranked         15800 non-null  float64
 17  Popularity     17562 non-null  int64
 18  Members        17562 non-null  int64
 19  Favorites      17562 non-null  int64
 20  Watching       17562 non-null  int64
 21  Completed      17562 non-null  int64
 22  On-Hold        17562 non-null  int64
 23  Dropped        17562 non-null  int64
 24  Plan to Watch  17562 non-null  int64
 25  Score-10       17125 non-null  float64
 26  Score-9        14395 non-null  float64
 27  Score-8        16191 non-null  float64
 28  Score-7        17059 non-null  float64
 29  Score-6        17051 non-null  float64
 30  Score-5        16978 non-null  float64
 31  Score-4        16585 non-null  float64
 32  Score-3        16255 non-null  float64
 33  Score-2        15965 non-null  float64
 34  Score-1        17103 non-null  float64
dtypes: float64(13), int64(9), object(13)
memory usage: 4.7+ MB

In [59]:
anime['Type'].value_counts()

Type
TV         4996
OVA        3894
Movie      3041
Special    2218
ONA        1907
Music      1469
Name: count, dtype: int64

In [60]:
anime['Source'].value_counts()

Source
Original         5215
Manga            3825
Visual novel      993
Game              880
Light novel       768
Other             597
Novel             510
Music             317
4-koma manga      288
Web manga         252
Picture book      147
Book              112
Card game          64
Digital manga      15
Radio              12
Name: count, dtype: int64

In [61]:
anime['Rating'].value_counts()

Rating
PG-13 - Teens 13 or older         6132
G - All Ages                      5782
PG - Children                     1461
Rx - Hentai                       1345
R - 17+ (violence & profanity)    1157
R+ - Mild Nudity                   997
Name: count, dtype: int64

In [62]:
genres = anime['Genres'].dropna().str.split(', ').explode()
print(genres.value_counts().head(15))

Genres
Comedy           6029
Action           3888
Fantasy          3285
Adventure        2957
Kids             2665
Drama            2619
Sci-Fi           2583
Music            2244
Shounen          2003
Slice of Life    1914
Romance          1899
School           1642
Supernatural     1479
Hentai           1348
Historical       1144
Name: count, dtype: int64

In [63]:
studios = anime['Studios'].dropna().str.split(', ').explode()
print(studios.value_counts().head(15))

Studios
Toei Animation          778
Sunrise                 502
J.C.Staff               382
Madhouse                364
Production I.G          335
TMS Entertainment       300
Studio Deen             287
Studio Pierrot          263
OLM                     237
Nippon Animation        217
A-1 Pictures            209
Shin-Ei Animation       178
DLE                     175
Tatsunoko Production    170
Xebec                   155
Name: count, dtype: int64

## Synthèse anime

| Anomalie | Détail | Action |
|----------|--------|--------|
| "Unknown" comme sentinelle | Masquait les vraies valeurs manquantes (0 null affiché par pandas) | Remplacé par NaN via `replace('Unknown', np.nan)` |
| Colonnes numériques en string | Score, Episodes, Ranked, Score-1 à Score-10 stockés en object | Convertis en float via `pd.to_numeric(errors='coerce')` |
| 4 noms dupliqués | Hinamatsuri (OVA vs TV), Youkoso! Ecolo Shima, Maou Gakuin (saisons) | Légitimes : MAL_ID distincts, pas de suppression |
| Premiered | 12 817 NaN (73%) | Normal : seuls les animes TV saisonniers ont une saison de première |
| Licensors | 13 616 NaN (77%) | Normal : beaucoup d'animes n'ont pas de distributeur occidental |
| English name | 10 565 NaN (60%) | Beaucoup d'animes n'ont pas de titre anglais officiel |
| Genres et Studios | Valeurs multi-valuées séparées par ", " | Exploitables après split, pas de nettoyage nécessaire |

# 4 EDA, Nettoyage et Audit de ratings_complete

In [64]:
rating_complete.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57633278 entries, 0 to 57633277
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   user_id   int64
 1   anime_id  int64
 2   rating    int64
dtypes: int64(3)
memory usage: 1.3 GB

In [65]:
rating_complete['rating'].value_counts()

rating
8     14642156
7     13325549
9      9773857
6      6849293
10     6716048
5      3436250
4      1455102
3       696048
2       405556
1       333419
Name: count, dtype: int64

In [66]:
rating_complete['rating'].describe()

count    5.763328e+07
mean     7.510789e+00
std      1.697722e+00
min      1.000000e+00
25%      7.000000e+00
50%      8.000000e+00
75%      9.000000e+00
max      1.000000e+01
Name: rating, dtype: float64

In [67]:
rating_complete.isnull().sum()

user_id     0
anime_id    0
rating      0
dtype: int64

In [68]:
rating_complete[['user_id', 'anime_id']].duplicated().sum()

np.int64(0)

In [69]:
rating_complete['user_id'].nunique()

310059

In [70]:
rating_complete['anime_id'].nunique()

16872

In [71]:
anime_ids = set(anime['MAL_ID'])
animelist_ids = set(animelist['anime_id'])
rating_ids = set(rating_complete['anime_id'])

print(f"anime_id dans animelist.csv mais pas dans anime.csv : {len(animelist_ids - anime_ids)}")
print(f"anime_id dans rating_complete.csv mais pas dans anime.csv : {len(rating_ids - anime_ids)}")

anime_id dans animelist.csv mais pas dans anime.csv : 0
anime_id dans rating_complete.csv mais pas dans anime.csv : 0

## Synthèse rating_complete

| Point | Détail |
|-------|--------|
| Nulls | 0 sur toutes les colonnes |
| Doublons | 0 (clé composite user_id + anime_id unique) |
| Users uniques | 310 059 |
| Animes uniques | 16 872 |
| Plage de notes | 1 à 10 (pas de 0 contrairement à animelist) |
| Distribution | Skew positif : médiane = 8, moyenne = 7.51 |
| Cohérence | 0 anime_id orphelins (tous présents dans anime.csv) |

**Ce fichier est propre et prêt à l'emploi.** Aucun nettoyage nécessaire.

# 5 EDA, Nettoyage et Audit de anime_with_synopsis

In [72]:
anime_with_synopsis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16214 entries, 0 to 16213
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   MAL_ID     16214 non-null  int64
 1   Name       16214 non-null  object
 2   Score      16214 non-null  object
 3   Genres     16214 non-null  object
 4   sypnopsis  16206 non-null  object
dtypes: int64(1), object(4)
memory usage: 633.5+ KB

In [73]:
anime_with_synopsis.isnull().sum()

MAL_ID       0
Name         0
Score        0
Genres       0
sypnopsis    8
dtype: int64

In [74]:
anime_with_synopsis = anime_with_synopsis.rename(columns={'sypnopsis': 'Synopsis'})

In [75]:
anime_with_synopsis.duplicated().sum()

np.int64(0)

In [76]:
anime_with_synopsis["MAL_ID"].duplicated().sum()

np.int64(0)

In [77]:
anime_with_synopsis['Synopsis'].str.len().describe()

count    16206.000000
mean       377.162471
std        340.194235
min         10.000000
25%        107.000000
50%        264.000000
75%        575.000000
max       3047.000000
Name: Synopsis, dtype: float64

In [78]:
(anime_with_synopsis['Synopsis'].str.len() < 50).sum()

np.int64(1375)

In [79]:
synopsis_ids = set(anime_with_synopsis['MAL_ID'])
anime_ids = set(anime['MAL_ID'])

print(f"Dans anime mais pas dans synopsis : {len(anime_ids - synopsis_ids)}")
print(f"Dans synopsis mais pas dans anime : {len(synopsis_ids - anime_ids)}")

Dans anime mais pas dans synopsis : 1348
Dans synopsis mais pas dans anime : 0

## Synthèse anime_with_synopsis

| Point | Détail |
|-------|--------|
| Colonne mal nommée | `sypnopsis` → renommée en `Synopsis` |
| Doublons | 0 (MAL_ID unique) |
| Couverture | 1348 animes dans anime.csv n'ont pas de synopsis |
| Orphelins | 0 (tous les MAL_ID de synopsis existent dans anime.csv) |
| Synopsis courts (< 50 chars) | À vérifier — potentiellement inutiles pour le full-text search |

# 6 Synthèse Intermèdiaire Et Prochaines Etapes

## Bilan qualité par fichier

| Fichier | Lignes | Qualité | Problèmes majeurs |
|---------|--------|---------|-------------------|
| animelist.csv | 109M | Moyenne | rating=0 (43%), watched_episodes=65535, watching_status aberrants |
| anime.csv | 17 562 | Faible | "Unknown" masquant les NaN, types incohérents, colonnes très incomplètes |
| rating_complete.csv | 57M | Bonne | Propre, aucun nettoyage nécessaire |
| anime_with_synopsis.csv | 16 214 | Bonne | Colonne mal nommée, 1348 animes sans synopsis |

## Actions de nettoyage à appliquer (Feature Engineering)

1. **animelist** : traiter les rating=0 (exclure ou flagger), corriger watched_episodes=65535 via croisement avec anime.csv
2. **anime** : conversions de types déjà faites, créer des features métier (score de popularité pondéré, ratio dropped/completed, classification studios)
3. **rating_complete** : prêt à l'emploi
4. **anime_with_synopsis** : merger avec anime.csv pour enrichir le dataset gold
5. **Export** : produire un dataset "gold" nettoyé et enrichi en CSV + JSON pour indexation dans Elasticsearch

# 7 Merge Dataset + Feature Engineering

In [80]:
anime_gold = anime.merge(anime_with_synopsis[['MAL_ID', 'Synopsis']], on='MAL_ID', how='left')

In [83]:

C = anime_gold['Score'].mean() 
m = anime_gold['Members'].quantile(0.25) 
anime_gold['weighted_score'] = ((anime_gold['Members'] * anime_gold['Score'] + m * C) / (anime_gold['Members'] + m))

In [84]:
studio_counts = anime_gold['Studios'].dropna().str.split(', ').explode().value_counts()
top_studios = set(studio_counts.head(20).index)
mid_studios = set(studio_counts.head(100).index) - top_studios

def classify_studio(s):
    if pd.isna(s):
        return 'unknown'
    main_studio = s.split(', ')[0]
    if main_studio in top_studios:
        return 'top'
    elif main_studio in mid_studios:
        return 'mid'
    return 'small'

anime_gold['studio_tier'] = anime_gold['Studios'].apply(classify_studio)
anime_gold['studio_tier'].value_counts()

studio_tier
unknown    7079
top        5095
mid        3341
small      2047
Name: count, dtype: int64

In [86]:
def parse_duration(df):
    if pd.isna(df):
        return np.nan
    hours = pd.Series(df).str.extract(r'(\d+)\s*hr')[0].values[0]
    mins = pd.Series(df).str.extract(r'(\d+)\s*min')[0].values[0]
    h = float(hours) if pd.notna(hours) else 0
    m = float(mins) if pd.notna(mins) else 0
    return h * 60 + m

anime_gold['duration_min'] = anime_gold['Duration'].apply(parse_duration)

In [87]:
anime_gold.to_csv('../data/anime_gold.csv', index=False)

In [88]:
anime_gold.to_json('../data/anime_gold.json', orient='records', force_ascii=False)